### ISSUE TITLE
Simpler docker image

### ISSUE THREAD

**Issue by wuputah** [HydrasDB/hydra#22]
A simpler docker image not based on Spilo, likely built on top of the [postgres](https://hub.docker.com/_/postgres/) image, that uses UID/GID 70.

(Feedback from #21)

**Comment by wuputah** [comment]
We've now shipped a postgres image! :tada:

**Comment by saul-data** [comment]
@wuputah Awesome! Can you please send the link? I'll set it up on my side. We can create some Hydra connectors for Dataplane's Python library.
